# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/connector.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/connector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/connector.proto\x12\x05proto\"\x07\n\x05\x45mpty\"U\n\nDataObject\x12\x11\n\tremote_id\x18\x01 \x01(\t\x12\x15\n\rresource_name\x18\x02 \x01(\t\x12\x0b\n\x03uri\x18\x03 \x01(\t\x12\x10\n\x08metadata\x18\x04 \x01(\t\"?\n\x0bSyncRequest\x12\x0f\n\x07options\x18\x01 \x01(\t\x12\x1f\n\x17\x63\x61llback_handler_server\x18\x02 \x01(\r\"3\n\x0cSyncResponse\x12#\n\x08response\x18\x01 \x03(\x0b\x32\x11.proto.DataObject\"\x1b\n\x07\x45ndSync\x12\x10\n\x08metadata\x18\x01 \x01(\t27\n\tConnector\x12*\n\x04Sync\x12\x12.proto.SyncRequest\x1a\x0e.proto.EndSync2@\n\x0f\x43\x61llbackHandler\x12-\n\x08\x43\x61llback\x12\x13.proto.SyncResponse\x1a\x0c.proto.EmptyB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.connector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_DATAOBJECT']._serialized_start=41
  _globals['_DATAOBJECT']._serialized_end=126
  _globals['_SYNCREQUEST']._serialized_start=128
  _globals['_SYNCREQUEST']._serialized_end=191
  _globals['_SYNCRESPONSE']._serialized_start=193
  _globals['_SYNCRESPONSE']._serialized_end=244
  _globals['_ENDSYNC']._serialized_start=246
  _globals['_ENDSYNC']._serialized_end=273
  _globals['_CONNECTOR']._serialized_start=275
  _globals['_CONNECTOR']._serialized_end=330
  _globals['_CALLBACKHANDLER']._serialized_start=332
  _globals['_CALLBACKHANDLER']._serialized_end=396
# @@protoc_insertion_point(module_scope)
